name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: build-test
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5.0.0
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #v5.5.0
      with:
        go-version: 1.21
    - name: Run tests
      run: go test github.com/lonegunmanb/hclmerge/...