name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: build-test
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #v5.0.2
      with:
        go-version: 1.21
    - name: Run tests
      run: go test github.com/lonegunmanb/hclmerge/...