name: build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: build-test
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
    - name: Set up Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a #v5.2.0
      with:
        go-version: 1.21
    - name: Run tests
      run: go test github.com/lonegunmanb/hclmerge/...