name: lint
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #v5.3.0
        with:
          go-version: 1.21
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
      - name: golangci-lint
        run: |
          docker run --rm -v $(pwd):/src -w /src golangci/golangci-lint golangci-lint run --timeout 1h --skip-dirs integration -v ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@d4617f51baf75f4f809066386a4f9d27b3ac3e46 #v2.21.4